import { prisma } from "../lib/prisma";
import bcrypt from "bcryptjs";
import { generateUniqueReferralCode } from "../lib/referral";

// govFeeEstimateSar is an indicative planning figure for what the government
// portal itself charges for the transaction - Mysorat never collects this, it
// is shown to the customer purely so they know what to expect when they
// complete the step on the official government site. It is NOT added to what
// Mysorat charges. The platform's own fee (platformFeeSar, computed below)
// is what actually gets charged via /operations/:id/pay.
const services = [
  // الهوية والأحوال المدنية
  {
    code: "NATIONAL_ID_ISSUE",
    nameAr: "إصدار بطاقة الهوية الوطنية",
    nameEn: "National ID Issuance",
    category: "الهوية والأحوال المدنية",
    descriptionAr: "إصدار بطاقة الهوية الوطنية لأول مرة للمواطنين.",
    targetAudience: ["CITIZEN"],
    estimatedDays: 3,
    govFeeEstimateSar: 0,
    requiredDocs: ["صورة شخصية حديثة", "شهادة الميلاد"],
  },
  {
    code: "NATIONAL_ID_RENEWAL",
    nameAr: "تجديد بطاقة الهوية الوطنية",
    nameEn: "National ID Renewal",
    category: "الهوية والأحوال المدنية",
    descriptionAr: "تجديد بطاقة الهوية الوطنية قبل أو بعد انتهاء صلاحيتها.",
    targetAudience: ["CITIZEN"],
    estimatedDays: 2,
    govFeeEstimateSar: 0,
    requiredDocs: ["البطاقة الحالية أو بلاغ فقدان"],
  },
  {
    code: "FAMILY_REGISTER",
    nameAr: "إصدار سجل الأسرة",
    nameEn: "Family Register Issuance",
    category: "الهوية والأحوال المدنية",
    descriptionAr: "إصدار أو تحديث سجل الأسرة الرسمي.",
    targetAudience: ["CITIZEN"],
    estimatedDays: 2,
    govFeeEstimateSar: 0,
    requiredDocs: ["شهادات ميلاد أفراد الأسرة", "عقد الزواج"],
  },
  {
    code: "BIRTH_CERTIFICATE",
    nameAr: "إصدار شهادة ميلاد",
    nameEn: "Birth Certificate Issuance",
    category: "الهوية والأحوال المدنية",
    descriptionAr: "إصدار شهادة ميلاد رسمية للمواليد الجدد.",
    targetAudience: ["CITIZEN", "RESIDENT"],
    estimatedDays: 1,
    govFeeEstimateSar: 0,
    requiredDocs: ["تقرير المستشفى", "هوية الوالدين"],
  },
  {
    code: "DEATH_CERTIFICATE",
    nameAr: "إصدار شهادة وفاة",
    nameEn: "Death Certificate Issuance",
    category: "الهوية والأحوال المدنية",
    descriptionAr: "إصدار شهادة وفاة رسمية.",
    targetAudience: ["CITIZEN", "RESIDENT"],
    estimatedDays: 1,
    govFeeEstimateSar: 0,
    requiredDocs: ["تقرير طبي بالوفاة", "هوية المتوفى"],
  },
  {
    code: "MARRIAGE_CONTRACT",
    nameAr: "توثيق عقد الزواج",
    nameEn: "Marriage Contract Documentation",
    category: "الهوية والأحوال المدنية",
    descriptionAr: "توثيق عقد الزواج إلكترونياً عبر منصة ناجز.",
    targetAudience: ["CITIZEN", "RESIDENT"],
    estimatedDays: 3,
    govFeeEstimateSar: 100,
    requiredDocs: ["هوية الزوجين", "هوية الشهود", "إذن ولي الأمر إن لزم"],
  },
  {
    code: "DIVORCE_DOCUMENTATION",
    nameAr: "توثيق الطلاق",
    nameEn: "Divorce Documentation",
    category: "الهوية والأحوال المدنية",
    descriptionAr: "توثيق إشهاد الطلاق إلكترونياً عبر منصة ناجز.",
    targetAudience: ["CITIZEN", "RESIDENT"],
    estimatedDays: 5,
    govFeeEstimateSar: 100,
    requiredDocs: ["عقد الزواج", "هوية الطرفين"],
  },

  // الإقامة والجوازات
  {
    code: "IQAMA_RENEWAL",
    nameAr: "تجديد الإقامة",
    nameEn: "Iqama Renewal",
    category: "الإقامة والجوازات",
    descriptionAr: "تجديد إقامة العامل أو المقيم قبل انتهاء صلاحيتها.",
    targetAudience: ["RESIDENT"],
    estimatedDays: 2,
    govFeeEstimateSar: 50,
    requiredDocs: ["صورة الإقامة الحالية", "تعهد سداد الرسوم"],
  },
  {
    code: "SPONSORSHIP_TRANSFER",
    nameAr: "نقل الكفالة",
    nameEn: "Sponsorship Transfer",
    category: "الإقامة والجوازات",
    descriptionAr: "نقل كفالة المقيم من كفيل حالي إلى كفيل جديد.",
    targetAudience: ["RESIDENT"],
    estimatedDays: 5,
    govFeeEstimateSar: 120,
    requiredDocs: ["موافقة الكفيل الحالي", "عقد العمل الجديد", "صورة الإقامة"],
  },
  {
    code: "PASSPORT_VISA",
    nameAr: "الجوازات والتأشيرات",
    nameEn: "Passports & Visas",
    category: "الإقامة والجوازات",
    descriptionAr: "استفسارات وإجراءات عامة تتعلق بجوازات السفر والتأشيرات.",
    targetAudience: ["CITIZEN", "RESIDENT"],
    estimatedDays: 3,
    govFeeEstimateSar: 80,
    requiredDocs: ["صورة جواز السفر", "صورة شخصية حديثة"],
  },
  {
    code: "EXIT_REENTRY_VISA",
    nameAr: "تأشيرة خروج وعودة",
    nameEn: "Exit-Re-Entry Visa",
    category: "الإقامة والجوازات",
    descriptionAr: "إصدار تأشيرة خروج وعودة للمقيم (فردية أو متعددة).",
    targetAudience: ["RESIDENT"],
    estimatedDays: 1,
    govFeeEstimateSar: 100,
    requiredDocs: ["صورة الإقامة", "تعهد الكفيل"],
  },
  {
    code: "FINAL_EXIT_VISA",
    nameAr: "تأشيرة الخروج النهائي",
    nameEn: "Final Exit Visa",
    category: "الإقامة والجوازات",
    descriptionAr: "إصدار تأشيرة الخروج النهائي لمغادرة المملكة بشكل نهائي.",
    targetAudience: ["RESIDENT"],
    estimatedDays: 2,
    govFeeEstimateSar: 0,
    requiredDocs: ["صورة الإقامة", "إخلاء طرف"],
  },
  {
    code: "FAMILY_VISIT_VISA",
    nameAr: "تأشيرة زيارة عائلية",
    nameEn: "Family Visit Visa",
    category: "الإقامة والجوازات",
    descriptionAr: "استقدام أحد الأقارب بتأشيرة زيارة عائلية.",
    targetAudience: ["CITIZEN", "RESIDENT"],
    estimatedDays: 5,
    govFeeEstimateSar: 300,
    requiredDocs: ["صورة جواز سفر الزائر", "إثبات صلة القرابة", "حجز فندقي أو سكن"],
  },

  // تأشيرات الزيارة والسياحة
  {
    code: "TOURIST_EVISA",
    nameAr: "التأشيرة السياحية الإلكترونية",
    nameEn: "Tourist eVisa",
    category: "تأشيرات الزيارة والسياحة",
    descriptionAr: "استخراج تأشيرة سياحية إلكترونية لزيارة المملكة.",
    targetAudience: ["VISITOR"],
    estimatedDays: 2,
    govFeeEstimateSar: 480,
    requiredDocs: ["صورة جواز السفر", "صورة شخصية"],
  },
  {
    code: "UMRAH_VISA",
    nameAr: "تأشيرة العمرة",
    nameEn: "Umrah Visa (Nusuk)",
    category: "تأشيرات الزيارة والسياحة",
    descriptionAr: "إصدار تأشيرة أداء العمرة عبر منصة نُسك.",
    targetAudience: ["VISITOR"],
    estimatedDays: 3,
    govFeeEstimateSar: 300,
    requiredDocs: ["صورة جواز السفر", "شهادة التطعيمات المطلوبة"],
  },
  {
    code: "VISIT_VISA_EXTENSION",
    nameAr: "تمديد تأشيرة الزيارة",
    nameEn: "Visit Visa Extension",
    category: "تأشيرات الزيارة والسياحة",
    descriptionAr: "تمديد مدة تأشيرة الزيارة السارية.",
    targetAudience: ["VISITOR"],
    estimatedDays: 2,
    govFeeEstimateSar: 200,
    requiredDocs: ["صورة جواز السفر", "صورة التأشيرة الحالية"],
  },
  {
    code: "VISITOR_TRAVEL_INSURANCE",
    nameAr: "تأمين السفر للزوار",
    nameEn: "Visitor Travel Insurance",
    category: "تأشيرات الزيارة والسياحة",
    descriptionAr: "إصدار وثيقة تأمين سفر تغطي مدة الزيارة.",
    targetAudience: ["VISITOR"],
    estimatedDays: 1,
    govFeeEstimateSar: 150,
    requiredDocs: ["صورة جواز السفر", "مدة الزيارة المتوقعة"],
  },

  // المرور والمركبات
  {
    code: "DRIVING_LICENSE_ISSUE",
    nameAr: "إصدار رخصة قيادة",
    nameEn: "Driving License Issuance",
    category: "المرور والمركبات",
    descriptionAr: "إصدار رخصة قيادة لأول مرة بعد اجتياز الاختبارات.",
    targetAudience: ["CITIZEN", "RESIDENT"],
    estimatedDays: 3,
    govFeeEstimateSar: 220,
    requiredDocs: ["شهادة اجتياز اختبار القيادة", "فحص النظر", "صورة شخصية"],
  },
  {
    code: "DRIVING_LICENSE_RENEWAL",
    nameAr: "تجديد رخصة القيادة",
    nameEn: "Driving License Renewal",
    category: "المرور والمركبات",
    descriptionAr: "تجديد رخصة القيادة السارية أو المنتهية.",
    targetAudience: ["CITIZEN", "RESIDENT"],
    estimatedDays: 1,
    govFeeEstimateSar: 40,
    requiredDocs: ["الرخصة الحالية"],
  },
  {
    code: "VEHICLE_REGISTRATION_RENEWAL",
    nameAr: "تجديد استمارة المركبة",
    nameEn: "Vehicle Registration Renewal",
    category: "المرور والمركبات",
    descriptionAr: "تجديد استمارة (رخصة سير) المركبة سنوياً.",
    targetAudience: ["CITIZEN", "RESIDENT"],
    estimatedDays: 1,
    govFeeEstimateSar: 100,
    requiredDocs: ["الاستمارة الحالية", "وثيقة التأمين", "شهادة الفحص الدوري"],
  },
  {
    code: "VEHICLE_OWNERSHIP_TRANSFER",
    nameAr: "نقل ملكية مركبة",
    nameEn: "Vehicle Ownership Transfer",
    category: "المرور والمركبات",
    descriptionAr: "نقل ملكية مركبة بين البائع والمشتري.",
    targetAudience: ["CITIZEN", "RESIDENT"],
    estimatedDays: 2,
    govFeeEstimateSar: 150,
    requiredDocs: ["استمارة المركبة", "هوية البائع والمشتري"],
  },
  {
    code: "TRAFFIC_VIOLATION_PAYMENT",
    nameAr: "سداد المخالفات المرورية",
    nameEn: "Traffic Violation Payment",
    category: "المرور والمركبات",
    descriptionAr: "الاستعلام عن المخالفات المرورية وسدادها.",
    targetAudience: ["CITIZEN", "RESIDENT", "VISITOR"],
    estimatedDays: 1,
    govFeeEstimateSar: 0,
    requiredDocs: ["رقم الهوية أو الإقامة أو جواز السفر"],
  },
  {
    code: "VEHICLE_INSURANCE",
    nameAr: "تأمين المركبات",
    nameEn: "Vehicle Insurance",
    category: "المرور والمركبات",
    descriptionAr: "إصدار أو تجديد وثيقة تأمين المركبة.",
    targetAudience: ["CITIZEN", "RESIDENT"],
    estimatedDays: 1,
    govFeeEstimateSar: 500,
    requiredDocs: ["استمارة المركبة", "رخصة القيادة"],
  },

  // الصحة
  {
    code: "HEALTH_APPOINTMENT",
    nameAr: "حجز موعد صحي",
    nameEn: "Health Appointment Booking (Sehhaty)",
    category: "الصحة",
    descriptionAr: "حجز موعد في مركز صحي أو مستشفى حكومي عبر صحتي.",
    targetAudience: ["CITIZEN", "RESIDENT", "VISITOR"],
    estimatedDays: 1,
    govFeeEstimateSar: 0,
    requiredDocs: ["رقم الهوية أو الإقامة أو جواز السفر"],
  },
  {
    code: "RESIDENT_HEALTH_INSURANCE",
    nameAr: "التأمين الصحي للمقيمين",
    nameEn: "Resident Health Insurance",
    category: "الصحة",
    descriptionAr: "إصدار أو تجديد وثيقة التأمين الصحي للمقيم.",
    targetAudience: ["RESIDENT"],
    estimatedDays: 2,
    govFeeEstimateSar: 600,
    requiredDocs: ["صورة الإقامة", "عقد العمل"],
  },
  {
    code: "VACCINATION_CERTIFICATE",
    nameAr: "شهادة التطعيمات",
    nameEn: "Vaccination Certificate",
    category: "الصحة",
    descriptionAr: "استخراج شهادة تطعيمات رسمية معتمدة.",
    targetAudience: ["CITIZEN", "RESIDENT", "VISITOR"],
    estimatedDays: 1,
    govFeeEstimateSar: 0,
    requiredDocs: ["سجل التطعيم الطبي"],
  },

  // التعليم
  {
    code: "CERTIFICATE_EQUIVALENCY",
    nameAr: "معادلة الشهادات الدراسية",
    nameEn: "Academic Certificate Equivalency",
    category: "التعليم",
    descriptionAr: "معادلة شهادة دراسية صادرة من خارج المملكة.",
    targetAudience: ["CITIZEN", "RESIDENT"],
    estimatedDays: 10,
    govFeeEstimateSar: 0,
    requiredDocs: ["الشهادة الأصلية", "كشف الدرجات", "ترجمة معتمدة"],
  },
  {
    code: "NOOR_REGISTRATION",
    nameAr: "التسجيل في نظام نور التعليمي",
    nameEn: "Noor Education System Registration",
    category: "التعليم",
    descriptionAr: "تسجيل الطالب في المدارس الحكومية عبر نظام نور.",
    targetAudience: ["CITIZEN", "RESIDENT"],
    estimatedDays: 2,
    govFeeEstimateSar: 0,
    requiredDocs: ["شهادة ميلاد الطالب", "سجل الأسرة"],
  },

  // الإسكان والعقار
  {
    code: "EJAR_RENTAL_CONTRACT",
    nameAr: "توثيق عقد الإيجار",
    nameEn: "Rental Contract Documentation (Ejar)",
    category: "الإسكان والعقار",
    descriptionAr: "توثيق عقد إيجار عقار سكني أو تجاري عبر منصة إيجار.",
    targetAudience: ["CITIZEN", "RESIDENT"],
    estimatedDays: 1,
    govFeeEstimateSar: 30,
    requiredDocs: ["هوية الطرفين", "صك ملكية العقار"],
  },
  {
    code: "PROPERTY_TITLE_DEED",
    nameAr: "إصدار صك ملكية عقار",
    nameEn: "Property Title Deed Issuance",
    category: "الإسكان والعقار",
    descriptionAr: "إصدار صك ملكية إلكتروني لعقار بعد إتمام البيع.",
    targetAudience: ["CITIZEN"],
    estimatedDays: 5,
    govFeeEstimateSar: 200,
    requiredDocs: ["عقد البيع", "هوية الأطراف"],
  },

  // البلدية والمرافق
  {
    code: "BUILDING_PERMIT",
    nameAr: "رخصة بناء",
    nameEn: "Building Permit (Balady)",
    category: "البلدية والمرافق",
    descriptionAr: "استخراج رخصة بناء عبر منصة بلدي.",
    targetAudience: ["CITIZEN", "BUSINESS"],
    estimatedDays: 10,
    govFeeEstimateSar: 500,
    requiredDocs: ["صك الملكية", "المخطط الهندسي المعتمد"],
  },
  {
    code: "ELECTRICITY_CONNECTION",
    nameAr: "توصيل الكهرباء",
    nameEn: "Electricity Connection",
    category: "البلدية والمرافق",
    descriptionAr: "طلب توصيل خدمة الكهرباء لعقار جديد.",
    targetAudience: ["CITIZEN", "RESIDENT", "BUSINESS"],
    estimatedDays: 5,
    govFeeEstimateSar: 300,
    requiredDocs: ["صك الملكية أو عقد الإيجار", "رخصة البناء"],
  },
  {
    code: "WATER_CONNECTION",
    nameAr: "توصيل المياه",
    nameEn: "Water Connection",
    category: "البلدية والمرافق",
    descriptionAr: "طلب توصيل خدمة المياه لعقار جديد.",
    targetAudience: ["CITIZEN", "RESIDENT", "BUSINESS"],
    estimatedDays: 5,
    govFeeEstimateSar: 250,
    requiredDocs: ["صك الملكية أو عقد الإيجار"],
  },

  // العدل والتوثيق
  {
    code: "POWER_OF_ATTORNEY",
    nameAr: "توثيق الوكالات",
    nameEn: "Power of Attorney Documentation",
    category: "العدل والتوثيق",
    descriptionAr: "توثيق وكالة شرعية إلكترونياً عبر منصة ناجز.",
    targetAudience: ["CITIZEN", "RESIDENT"],
    estimatedDays: 1,
    govFeeEstimateSar: 50,
    requiredDocs: ["هوية الموكل والوكيل"],
  },
  {
    code: "ECOURT_FILING",
    nameAr: "رفع دعوى قضائية إلكترونية",
    nameEn: "E-Court Case Filing (Najiz)",
    category: "العدل والتوثيق",
    descriptionAr: "رفع دعوى قضائية إلكترونياً دون الحاجة لمراجعة المحكمة.",
    targetAudience: ["CITIZEN", "RESIDENT"],
    estimatedDays: 7,
    govFeeEstimateSar: 50,
    requiredDocs: ["صحيفة الدعوى", "المستندات المؤيدة"],
  },

  // الأعمال والاستثمار
  {
    code: "COMMERCIAL_REGISTRY",
    nameAr: "السجل التجاري والتراخيص",
    nameEn: "Commercial Registry & Licensing",
    category: "الأعمال والاستثمار",
    descriptionAr: "إصدار أو تجديد السجل التجاري ورخص النشاط.",
    targetAudience: ["BUSINESS"],
    estimatedDays: 4,
    govFeeEstimateSar: 200,
    requiredDocs: ["عقد التأسيس", "إثبات العنوان الوطني", "صورة الهوية"],
  },
  {
    code: "MISA_INVESTMENT",
    nameAr: "الاستثمار الأجنبي",
    nameEn: "Foreign Investment License (MISA)",
    category: "الأعمال والاستثمار",
    descriptionAr: "إصدار ترخيص استثمار أجنبي عبر وزارة الاستثمار.",
    targetAudience: ["BUSINESS"],
    estimatedDays: 7,
    govFeeEstimateSar: 2000,
    requiredDocs: ["خطة العمل", "إثبات رأس المال", "جواز السفر", "السجل التجاري بالدولة الأم"],
  },
  {
    code: "BALADY_BUSINESS_LICENSE",
    nameAr: "رخصة بلدية للنشاط التجاري",
    nameEn: "Municipal Business License (Balady)",
    category: "الأعمال والاستثمار",
    descriptionAr: "استخراج رخصة بلدية لمزاولة نشاط تجاري.",
    targetAudience: ["BUSINESS"],
    estimatedDays: 5,
    govFeeEstimateSar: 300,
    requiredDocs: ["عقد الإيجار التجاري", "السجل التجاري"],
  },
  {
    code: "ETIMAD_REGISTRATION",
    nameAr: "التسجيل في منصة اعتماد",
    nameEn: "Etimad Government Procurement Registration",
    category: "الأعمال والاستثمار",
    descriptionAr: "التسجيل كمورد للمشتريات الحكومية عبر منصة اعتماد.",
    targetAudience: ["BUSINESS"],
    estimatedDays: 3,
    govFeeEstimateSar: 0,
    requiredDocs: ["السجل التجاري", "الشهادات الضريبية"],
  },

  // المالية
  {
    code: "ZATCA_TAX",
    nameAr: "الزكاة والضريبة",
    nameEn: "Zakat & Tax (ZATCA)",
    category: "المالية",
    descriptionAr: "تقديم إقرارات الزكاة والضريبة وسداد المستحقات.",
    targetAudience: ["BUSINESS"],
    estimatedDays: 3,
    govFeeEstimateSar: 100,
    requiredDocs: ["القوائم المالية", "السجل التجاري"],
  },
  {
    code: "VAT_REGISTRATION",
    nameAr: "التسجيل في ضريبة القيمة المضافة",
    nameEn: "VAT Registration",
    category: "المالية",
    descriptionAr: "تسجيل المنشأة في ضريبة القيمة المضافة.",
    targetAudience: ["BUSINESS"],
    estimatedDays: 3,
    govFeeEstimateSar: 0,
    requiredDocs: ["السجل التجاري", "القوائم المالية"],
  },

  // الموارد البشرية
  {
    code: "GOSI",
    nameAr: "التأمينات الاجتماعية",
    nameEn: "Social Insurance (GOSI)",
    category: "الموارد البشرية",
    descriptionAr: "تسجيل الموظفين والاشتراك في التأمينات الاجتماعية.",
    targetAudience: ["BUSINESS"],
    estimatedDays: 2,
    govFeeEstimateSar: 60,
    requiredDocs: ["كشف الرواتب", "عقود الموظفين"],
  },
  {
    code: "MUDAD_HR",
    nameAr: "الموارد البشرية (مساند)",
    nameEn: "HR Services (Mudad)",
    category: "الموارد البشرية",
    descriptionAr: "إدارة عقود العمل واعتماد الرواتب عبر مساند.",
    targetAudience: ["BUSINESS"],
    estimatedDays: 2,
    govFeeEstimateSar: 60,
    requiredDocs: ["كشف الرواتب", "بيانات الموظفين"],
  },
  {
    code: "UNEMPLOYMENT_INSURANCE_SANED",
    nameAr: "تأمين ساند للتعطل عن العمل",
    nameEn: "SANED Unemployment Insurance",
    category: "الموارد البشرية",
    descriptionAr: "التقديم على معاش التعطل عن العمل (ساند) للمواطن.",
    targetAudience: ["CITIZEN"],
    estimatedDays: 3,
    govFeeEstimateSar: 0,
    requiredDocs: ["الهوية الوطنية", "إثبات إنهاء الخدمة"],
  },
] as const;

const links = [
  { nameAr: "أبشر", nameEn: "Absher", url: "https://www.absher.sa", category: "الإقامة والجوازات" },
  { nameAr: "منصة ناجز", nameEn: "Najiz", url: "https://najiz.sa", category: "العدل والتوثيق" },
  { nameAr: "منصة أبشر أفراد", nameEn: "Absher Individuals", url: "https://www.absher.sa/wps/portal/individuals", category: "الهوية والأحوال المدنية" },
  { nameAr: "منصة نُسك", nameEn: "Nusuk", url: "https://nusuk.sa", category: "تأشيرات الزيارة والسياحة" },
  { nameAr: "التأشيرة السياحية السعودية", nameEn: "Visit Saudi eVisa", url: "https://visa.visitsaudi.com", category: "تأشيرات الزيارة والسياحة" },
  { nameAr: "أبشر مركبتي", nameEn: "Absher Vehicles", url: "https://www.absher.sa", category: "المرور والمركبات" },
  { nameAr: "صحتي", nameEn: "Sehhaty", url: "https://sehhaty.sa", category: "الصحة" },
  { nameAr: "نظام نور", nameEn: "Noor", url: "https://noor.moe.gov.sa", category: "التعليم" },
  { nameAr: "منصة إيجار", nameEn: "Ejar", url: "https://ejar.sa", category: "الإسكان والعقار" },
  { nameAr: "منصة بلدي", nameEn: "Balady", url: "https://balady.gov.sa", category: "البلدية والمرافق" },
  { nameAr: "منصة اعتماد", nameEn: "Etimad", url: "https://etimad.sa", category: "الأعمال والاستثمار" },
  { nameAr: "وزارة الاستثمار", nameEn: "MISA", url: "https://misa.gov.sa", category: "الأعمال والاستثمار" },
  { nameAr: "هيئة الزكاة والضريبة والجمارك", nameEn: "ZATCA", url: "https://zatca.gov.sa", category: "المالية" },
  { nameAr: "التأمينات الاجتماعية", nameEn: "GOSI", url: "https://gosi.gov.sa", category: "الموارد البشرية" },
  { nameAr: "منصة قوى", nameEn: "Qiwa", url: "https://qiwa.sa", category: "الموارد البشرية" },
  { nameAr: "منصة ساند", nameEn: "SANED", url: "https://saned.gosi.gov.sa", category: "الموارد البشرية" },
  { nameAr: "وزارة التجارة", nameEn: "MCI", url: "https://mc.gov.sa", category: "الأعمال والاستثمار" },
];

// Mysorat's own assistance fee reflects the platform's effort (AI guidance,
// tracking, document handling) - deliberately derived from estimatedDays
// rather than from govFeeEstimateSar, so it can never look like a markup on
// the government's own charge.
function computePlatformFeeSar(estimatedDays: number): number {
  return Math.min(30, Math.max(10, estimatedDays * 3));
}

export async function seedDatabase() {
  const ownerEmail = process.env.OWNER_EMAIL?.trim() ?? "owner@mysorat.sa";
  const ownerPassword = process.env.OWNER_PASSWORD?.trim() ?? "ChangeMe123!";

  const owner = await prisma.user.upsert({
    where: { email: ownerEmail },
    create: {
      email: ownerEmail,
      passwordHash: await bcrypt.hash(ownerPassword, 12),
      role: "OWNER",
      referralCode: await generateUniqueReferralCode(),
    },
    update: {},
  });

  for (const service of services) {
    const data = {
      ...service,
      requiredDocs: [...service.requiredDocs],
      targetAudience: [...service.targetAudience],
      platformFeeSar: computePlatformFeeSar(service.estimatedDays),
    };
    await prisma.serviceCatalog.upsert({ where: { code: service.code }, create: data, update: data });
  }

  let linksCreated = 0;
  for (const link of links) {
    const existing = await prisma.governmentLink.findFirst({ where: { url: link.url } });
    if (!existing) {
      await prisma.governmentLink.create({ data: link });
      linksCreated++;
    }
  }

  return {
    ownerEmail: owner.email,
    servicesUpserted: services.length,
    linksCreated,
  };
}
